<?php

return [
    'modules' => [
        [
            'module' => 'Module 1',
            'slug' => 'module-1',
            'week' => 'Week 1',
            'week_number' => 1,
            'start' => 'Mon, Jun 22, 2026',
            'title' => 'Introduction to PHP & Dev Environment Setup',
            'description' => 'Start with PHP basics, local development, Laravel Herd, and the first rendered coursework page.',
            'status' => 'Open',
            'accent' => 'teal',
            'assignments' => [
                [
                    'label' => 'Assignment 1A',
                    'title' => 'Laravel Hello World',
                    'description' => 'Create the first Laravel route and render a clean Blade page.',
                    'status' => 'Ready',
                    'route' => 'assignments.module1.assignment1a',
                ],
            ],
            'resources' => ['PHP local setup', 'Laravel project structure', 'Blade view basics'],
            'notes' => ['Focus on routes, views, and a repeatable local development setup.'],
        ],
        [
            'module' => 'Module 2',
            'slug' => 'module-2',
            'week' => 'Week 1',
            'week_number' => 1,
            'start' => 'Mon, Jun 22, 2026',
            'title' => 'Control Structures & Loops',
            'description' => 'Practice if statements, conditional branches, loops, and dynamic PHP output.',
            'status' => 'Open',
            'accent' => 'coral',
            'assignments' => [
                [
                    'label' => 'Assignment 2A',
                    'title' => 'T-Shirt Price Engine',
                    'description' => 'Use conditionals to calculate a final custom shirt price.',
                    'status' => 'Ready',
                    'type' => 'PHP',
                    'url' => '/module2a/price_engine.php',
                ],
                [
                    'label' => 'Assignment 2A Refactor',
                    'title' => 'Price Engine Refactored',
                    'description' => 'Clean up repeated logic with clearer branching.',
                    'status' => 'Ready',
                    'type' => 'PHP',
                    'url' => '/module2a/price_engine_refactored.php',
                ],
                [
                    'label' => 'Assignment 2B',
                    'title' => 'Cosmic Calendar',
                    'description' => 'Use API date data and loops to render a day-number calendar.',
                    'status' => 'Ready',
                    'type' => 'Laravel',
                    'route' => 'assignments.module2.cosmic-calendar',
                ],
            ],
            'resources' => ['Conditionals', 'Loops', 'Date and time data'],
            'notes' => ['The module links the calculation logic from Assignment 2A with loop rendering from Assignment 2B.'],
        ],
        [
            'module' => 'Module 3',
            'slug' => 'module-3',
            'week' => 'Week 2',
            'week_number' => 2,
            'start' => 'Mon, Jun 29, 2026',
            'title' => 'Handling Web Requests (Forms & Security)',
            'description' => 'Work with forms, request data, validation, CSRF protection, redirects, and safe user input.',
            'status' => 'Scheduled',
            'accent' => 'sky',
            'assignments' => [],
            'resources' => ['Forms', 'Request lifecycle', 'Validation and CSRF'],
            'notes' => ['This is where PHP moves from static output into user-submitted data.'],
        ],
        [
            'module' => 'Module 4',
            'slug' => 'module-4',
            'week' => 'Week 2',
            'week_number' => 2,
            'start' => 'Mon, Jun 29, 2026',
            'title' => 'Database Fundamentals (SQL & MySQL)',
            'description' => 'Learn tables, records, relationships, SQL queries, and MySQL-backed application storage.',
            'status' => 'Scheduled',
            'accent' => 'gold',
            'assignments' => [],
            'resources' => ['SQL basics', 'MySQL', 'Relational data modeling'],
            'notes' => ['Focus on how data is shaped before Eloquent and migrations arrive.'],
        ],
        [
            'module' => 'Module 5',
            'slug' => 'module-5',
            'week' => 'Week 3',
            'week_number' => 3,
            'start' => 'Mon, Jul 6, 2026',
            'title' => 'Object Oriented Programming',
            'description' => 'Organize PHP code with classes, objects, properties, methods, visibility, and simple design boundaries.',
            'status' => 'Scheduled',
            'accent' => 'violet',
            'assignments' => [],
            'resources' => ['Classes and objects', 'Methods and properties', 'Visibility'],
            'notes' => ['This module prepares the project for service classes and clearer responsibilities.'],
        ],
        [
            'module' => 'Module 6',
            'slug' => 'module-6',
            'week' => 'Week 3',
            'week_number' => 3,
            'start' => 'Mon, Jul 6, 2026',
            'title' => 'Autoloading, Composer & the MVC Pattern',
            'description' => 'Connect files, dependencies, controllers, views, and models into a clean application flow.',
            'status' => 'Scheduled',
            'accent' => 'teal',
            'assignments' => [],
            'resources' => ['Composer autoloading', 'MVC', 'Package hygiene'],
            'notes' => ['Composer and MVC explain why Laravel projects are not usually built as one-file scripts.'],
        ],
        [
            'module' => 'Module 7',
            'slug' => 'module-7',
            'week' => 'Week 4',
            'week_number' => 4,
            'start' => 'Mon, Jul 13, 2026',
            'title' => 'Intro to Laravel',
            'description' => 'Move deeper into Laravel routes, controllers, Blade views, layouts, and framework conventions.',
            'status' => 'Scheduled',
            'accent' => 'coral',
            'assignments' => [],
            'resources' => ['Routes', 'Controllers', 'Blade layouts'],
            'notes' => ['This is the bridge from PHP fundamentals into a real Laravel application.'],
        ],
        [
            'module' => 'Module 8',
            'slug' => 'module-8',
            'week' => 'Week 4',
            'week_number' => 4,
            'start' => 'Mon, Jul 13, 2026',
            'title' => 'ORM & Database Migrations (Eloquent)',
            'description' => 'Use Eloquent and migrations to describe, evolve, and query application data.',
            'status' => 'Scheduled',
            'accent' => 'sky',
            'assignments' => [],
            'resources' => ['Eloquent models', 'Migrations', 'Database relationships'],
            'notes' => ['Migrations make database structure reviewable in Git instead of hidden in a local database.'],
        ],
        [
            'module' => 'Module 9',
            'slug' => 'module-9',
            'week' => 'Week 5',
            'week_number' => 5,
            'start' => 'Mon, Jul 20, 2026',
            'title' => 'Full CRUD & Validation',
            'description' => 'Build create, read, update, and delete flows with validation rules and user feedback.',
            'status' => 'Scheduled',
            'accent' => 'gold',
            'assignments' => [],
            'resources' => ['CRUD workflows', 'Form requests', 'Validation errors'],
            'notes' => ['CRUD is where routing, forms, models, and database work come together.'],
        ],
        [
            'module' => 'Module 10',
            'slug' => 'module-10',
            'week' => 'Week 5',
            'week_number' => 5,
            'start' => 'Mon, Jul 20, 2026',
            'title' => 'User Authentication',
            'description' => 'Add login, logout, protected screens, user-aware behavior, roles, and secure account flows.',
            'status' => 'Scheduled',
            'accent' => 'violet',
            'assignments' => [],
            'resources' => ['Sessions', 'Authentication', 'Authorization'],
            'notes' => ['Authentication turns the coursework site into a user-aware application.'],
        ],
        [
            'module' => 'Module 11',
            'slug' => 'module-11',
            'week' => 'Week 6',
            'week_number' => 6,
            'start' => 'Mon, Jul 27, 2026',
            'title' => 'Clean Architecture & Consuming APIs',
            'description' => 'Separate responsibilities and consume external APIs without mixing framework, domain, and presentation logic.',
            'status' => 'Scheduled',
            'accent' => 'teal',
            'assignments' => [],
            'resources' => ['Service classes', 'API clients', 'Clean boundaries'],
            'notes' => ['The Module 2B calendar is an early example: controller, service, and Blade view each have a job.'],
        ],
        [
            'module' => 'Module 12',
            'slug' => 'module-12',
            'week' => 'Week 6',
            'week_number' => 6,
            'start' => 'Mon, Jul 27, 2026',
            'title' => 'AI Integration, Career Tips & Final Project',
            'description' => 'Bring the course skills together with AI integration, portfolio polish, deployment notes, and final project planning.',
            'status' => 'Scheduled',
            'accent' => 'coral',
            'assignments' => [],
            'resources' => ['OpenAI integration', 'Career preparation', 'Final project polish'],
            'notes' => ['AI work should keep API keys server-side and make privacy/cost boundaries visible.'],
        ],
    ],

    'stack' => [
        [
            'category' => 'Application',
            'items' => ['PHP', 'Laravel', 'Blade', 'Vite'],
        ],
        [
            'category' => 'Data',
            'items' => ['SQLite for quick startup', 'MySQL-ready configuration', 'Migrations', 'Seeders'],
        ],
        [
            'category' => 'Quality',
            'items' => ['PHPUnit feature tests', 'Laravel Pint', 'npm audit', 'Build verification'],
        ],
        [
            'category' => 'Future AI',
            'items' => ['OpenAI PHP client', 'Server-side API key handling', 'Final project extension point'],
        ],
    ],

    'contact' => [
        'email' => 'serge.hall.dev@gmail.com',
        'profiles' => [
            [
                'label' => 'Coursework Website',
                'handle' => 'webdev-coursework.com',
                'href' => 'https://webdev-coursework.com',
                'description' => 'Learning reports, coursework progress, and web development portfolio notes.',
            ],
            [
                'label' => 'GitHub',
                'handle' => 'SergeHall',
                'href' => 'https://github.com/SergeHall',
                'description' => 'Code, backend systems, platform work, and shipping history.',
            ],
        ],
        'topics' => [
            'Course questions and CS85 assignment planning.',
            'Laravel architecture, database design, and backend implementation.',
            'AI-powered final project ideas and responsible API integration.',
            'Portfolio polish, deployment readiness, and GitHub presentation.',
        ],
    ],
];
