<?php

return [
    'modules' => [
        [
            'module' => 'Module 1',
            'slug' => 'php-fundamentals',
            'week' => 'Week 1',
            'title' => 'PHP Fundamentals',
            'description' => 'Variables, types, operators, control structures, arrays, and local IDE setup.',
            'status' => 'Foundation',
            'assignments' => [],
            'resources' => [],
            'notes' => [],
        ],
        [
            'module' => 'Module 2',
            'slug' => 'oop-php',
            'week' => 'Week 2',
            'title' => 'Object-Oriented PHP',
            'description' => 'Classes, objects, methods, visibility, inheritance, and basic design boundaries.',
            'status' => 'Foundation',
            'assignments' => [],
            'resources' => [],
            'notes' => [],
        ],
        [
            'module' => 'Module 3',
            'slug' => 'forms-http-requests',
            'week' => 'Week 3',
            'title' => 'Forms and HTTP Requests',
            'description' => 'Form handling, request data, validation habits, CSRF protection, and redirects.',
            'status' => 'Prepared',
            'assignments' => [],
            'resources' => [],
            'notes' => [],
        ],
        [
            'module' => 'Module 4',
            'slug' => 'composer-packages',
            'week' => 'Week 3',
            'title' => 'Composer and Packages',
            'description' => 'Composer workflows, autoloading, dependencies, scripts, Pint, PHPStan, and package hygiene.',
            'status' => 'Prepared',
            'assignments' => [],
            'resources' => [],
            'notes' => [],
        ],
        [
            'module' => 'Module 5',
            'slug' => 'laravel-routing-views',
            'week' => 'Week 4',
            'title' => 'Laravel Routing and Views',
            'description' => 'Routes, Blade templates, layout composition, controllers, and user-facing pages.',
            'status' => 'Prepared',
            'assignments' => [],
            'resources' => [],
            'notes' => [],
        ],
        [
            'module' => 'Module 6',
            'slug' => 'mysql-database-operations',
            'week' => 'Week 5',
            'title' => 'MySQL and Database Operations',
            'description' => 'Schema design, migrations, CRUD workflows, Eloquent models, and query safety.',
            'status' => 'Prepared',
            'assignments' => [],
            'resources' => [],
            'notes' => [],
        ],
        [
            'module' => 'Module 7',
            'slug' => 'laravel-core-features',
            'week' => 'Week 6',
            'title' => 'Laravel Core Features',
            'description' => 'Sessions, authentication, authorization, validation, middleware, policies, and security headers.',
            'status' => 'Prepared',
            'assignments' => [],
            'resources' => [],
            'notes' => [],
        ],
        [
            'module' => 'Module 8',
            'slug' => 'ai-final-project',
            'week' => 'Week 6',
            'title' => 'AI-Powered Final Project',
            'description' => 'OpenAI integration, server-side API keys, privacy boundaries, cost control, and portfolio polish.',
            'status' => 'Planned',
            'assignments' => [],
            'resources' => [],
            'notes' => [],
        ],
    ],

    'stack' => [
        [
            'category' => 'Application',
            'items' => ['PHP', 'Laravel', 'Blade', 'Vite'],
        ],
        [
            'category' => 'Data',
            'items' => ['SQLite for quick startup', 'MySQL-ready configuration', 'Migrations', 'Seeders'],
        ],
        [
            'category' => 'Quality',
            'items' => ['PHPUnit feature tests', 'Laravel Pint', 'npm audit', 'Build verification'],
        ],
        [
            'category' => 'Future AI',
            'items' => ['OpenAI PHP client', 'Server-side API key handling', 'Final project extension point'],
        ],
    ],

    'contact' => [
        'email' => 'serge.hall.dev@gmail.com',
        'profiles' => [
            [
                'label' => 'Coursework Website',
                'handle' => 'webdev-coursework.com',
                'href' => 'https://webdev-coursework.com',
                'description' => 'Learning reports, coursework progress, and web development portfolio notes.',
            ],
            [
                'label' => 'GitHub',
                'handle' => 'SergeHall',
                'href' => 'https://github.com/SergeHall',
                'description' => 'Code, backend systems, platform work, and shipping history.',
            ],
        ],
        'topics' => [
            'Course questions and CS85 assignment planning.',
            'Laravel architecture, database design, and backend implementation.',
            'AI-powered final project ideas and responsible API integration.',
            'Portfolio polish, deployment readiness, and GitHub presentation.',
        ],
    ],
];
