<?php

return [
    'modules' => [
        [
            'module' => 'Module 1',
            'slug' => 'module-1',
            'week' => 'Week 1',
            'week_number' => 1,
            'start' => 'Mon, Jun 22, 2026',
            'title' => 'Introduction to PHP & Dev Environment Setup',
            'description' => 'Start with PHP basics, local development, Laravel Herd, and the first rendered coursework page.',
            'status' => 'Open',
            'accent' => 'teal',
            'assignments' => [
                [
                    'label' => 'Assignment 1A',
                    'title' => 'Laravel Hello World',
                    'description' => 'Create the first Laravel route and render a clean Blade page.',
                    'status' => 'Ready',
                    'route' => 'assignments.module1.assignment1a',
                    'source' => 'resources/views/pages/assignments/module1/assignment1a.blade.php',
                ],
            ],
            'resources' => ['PHP local setup', 'Laravel project structure', 'Blade view basics'],
            'notes' => ['Focus on routes, views, and a repeatable local development setup.'],
        ],
        [
            'module' => 'Module 2',
            'slug' => 'module-2',
            'week' => 'Week 1',
            'week_number' => 1,
            'start' => 'Mon, Jun 22, 2026',
            'title' => 'Control Structures & Loops',
            'description' => 'Practice if statements, conditional branches, loops, and dynamic PHP output.',
            'status' => 'Open',
            'accent' => 'coral',
            'assignments' => [
                [
                    'label' => 'Assignment 2A',
                    'title' => 'T-Shirt Price Engine',
                    'description' => 'Use conditionals to calculate a final custom shirt price.',
                    'status' => 'Ready',
                    'type' => 'PHP',
                    'url' => '/assignments/module2a/price_engine.php',
                    'source' => 'assignments/module2a/price_engine.php',
                ],
                [
                    'label' => 'Assignment 2A Refactor',
                    'title' => 'Price Engine Refactored',
                    'description' => 'Clean up repeated logic with clearer branching.',
                    'status' => 'Ready',
                    'type' => 'PHP',
                    'url' => '/assignments/module2a/price_engine_refactored.php',
                    'source' => 'assignments/module2a/price_engine_refactored.php',
                ],
                [
                    'label' => 'Assignment 2B',
                    'title' => 'Cosmic Calendar',
                    'description' => 'Use API date data and loops to render a day-number calendar.',
                    'status' => 'Ready',
                    'type' => 'Laravel',
                    'route' => 'assignments.module2.cosmic-calendar',
                    'source' => 'app/Http/Controllers/Assignments/Module2BCosmicCalendarController.php',
                ],
            ],
            'resources' => ['Conditionals', 'Loops', 'Date and time data'],
            'notes' => ['The module links the calculation logic from Assignment 2A with loop rendering from Assignment 2B.'],
        ],
        [
            'module' => 'Module 3',
            'slug' => 'module-3',
            'week' => 'Week 2',
            'week_number' => 2,
            'start' => 'Mon, Jun 29, 2026',
            'title' => 'Handling Web Requests (Forms & Security)',
            'description' => 'Work with forms, request data, validation, CSRF protection, redirects, and safe user input.',
            'status' => 'Open',
            'accent' => 'sky',
            'assignments' => [
                [
                    'label' => 'Assignment 3A',
                    'title' => 'Review and Comment on Form',
                    'description' => 'Analyze a PHP contact form, explain validation and sticky form behavior, and add a reflection.',
                    'status' => 'Ready',
                    'type' => 'PHP',
                    'url' => '/assignments/module3a/ContactForm.php',
                    'source' => 'assignments/module3a/ContactForm.php',
                ],
                [
                    'label' => 'Assignment 3B',
                    'title' => 'Secure Product Contact Form',
                    'description' => 'Build the next contact form with stronger request handling and security controls.',
                    'status' => 'Ready',
                    'type' => 'PHP',
                    'url' => '/assignments/module3b/SecureProductContactForm.php',
                    'source' => 'assignments/module3b/SecureProductContactForm.php',
                ],
                [
                    'label' => 'Quiz',
                    'title' => 'Module 3 - Handling Web Requests',
                    'description' => 'Review form processing, request data, validation, and basic web-request security concepts.',
                    'status' => 'Scheduled',
                    'type' => 'Quiz',
                ],
            ],
            'resources' => ['Forms', 'Request lifecycle', 'Validation and CSRF'],
            'notes' => ['This is where PHP moves from static output into user-submitted data.', 'Assignment 3A preserves the course script style, then documents the security improvements a professional app would need.', 'Assignment 3B adds POST handling, output escaping, and server-side validation for a secure product contact form.'],
        ],
        [
            'module' => 'Module 4',
            'slug' => 'module-4',
            'week' => 'Week 2',
            'week_number' => 2,
            'start' => 'Mon, Jun 29, 2026',
            'title' => 'Database Fundamentals (SQL & MySQL)',
            'description' => 'Learn tables, records, relationships, SQL queries, and MySQL-backed application storage.',
            'status' => 'Open',
            'accent' => 'gold',
            'assignments' => [
                [
                    'label' => 'Assignment 4A',
                    'title' => 'Database Setup',
                    'description' => 'Confirm PHP, MySQL, and phpMyAdmin are ready with a setup report and optional live connection check.',
                    'status' => 'Ready',
                    'type' => 'PHP + MySQL',
                    'url' => '/assignments/module4a/database-setup.php',
                    'source' => 'assignments/module4a/database-setup.php',
                ],
                [
                    'label' => 'Assignment 4B',
                    'title' => 'Personal Inventory Database',
                    'description' => 'Display personal inventory records from MySQL using PDO, prepared statements, and escaped table output.',
                    'status' => 'Ready',
                    'type' => 'PDO + MYSQL',
                    'url' => '/assignments/module4b/show_inventory.php',
                    'source' => 'assignments/module4b/show_inventory.php',
                ],
            ],
            'resources' => ['SQL basics', 'MySQL', 'phpMyAdmin', 'Laravel Herd or XAMPP'],
            'notes' => ['Focus on how data is shaped before Eloquent and migrations arrive.', 'Assignment 4A demonstrates the local database environment through a clickable setup report form.', 'Assignment 4B retrieves personal inventory records from MySQL with PDO and renders them safely in a table.'],
        ],
        [
            'module' => 'Module 5',
            'slug' => 'module-5',
            'week' => 'Week 3',
            'week_number' => 3,
            'start' => 'Mon, Jul 6, 2026',
            'title' => 'Object Oriented Programming',
            'description' => 'Organize PHP code with classes, objects, properties, methods, visibility, and simple design boundaries.',
            'status' => 'Open',
            'accent' => 'violet',
            'assignments' => [
                [
                    'label' => 'Assignment 5A',
                    'title' => 'Designing Your Own Object Oriented World',
                    'description' => 'Build an interactive SERGIOARTG photography booking object with quote calculation, deposit tracking, status changes, decision logic, and an AI method critique.',
                    'status' => 'Ready',
                    'type' => 'PHP OOP',
                    'url' => '/assignments/module5a/MyObject.php',
                    'source' => 'assignments/module5a/MyObject.php',
                ],
            ],
            'resources' => ['Classes and objects', 'Methods and properties', 'Visibility'],
            'notes' => [
                'This module prepares the project for service classes and clearer responsibilities.',
                'Assignment 5A models the SERGIOARTG photography booking workflow with properties, methods, constructor initialization, object instances, and method-level decision logic.',
                'The AI critique lives beside the PHP page at assignments/module5a/critique.md.',
            ],
        ],
        [
            'module' => 'Module 6',
            'slug' => 'module-6',
            'week' => 'Week 3',
            'week_number' => 3,
            'start' => 'Mon, Jul 6, 2026',
            'title' => 'Autoloading, Composer & the MVC Pattern',
            'description' => 'Connect files, dependencies, controllers, views, and models into a clean application flow.',
            'status' => 'Open',
            'accent' => 'teal',
            'assignments' => [
                [
                    'label' => 'Assignment 6A',
                    'title' => 'MVC-Based PHP Application',
                    'description' => 'Build a SERGIOARTG booking planner using Composer PSR-4 autoloading, a Model, a Controller, a View, validation, reflection, and AI critique.',
                    'status' => 'Ready',
                    'type' => 'PHP MVC',
                    'url' => '/assignments/module6a/public/index.php',
                    'source' => 'assignments/module6a/public/index.php',
                ],
            ],
            'resources' => ['Composer autoloading', 'MVC', 'Package hygiene'],
            'notes' => [
                'Composer and MVC explain why Laravel projects are not usually built as one-file scripts.',
                'Assignment 6A separates the SERGIOARTG booking planner into Model, Controller, View, and public entry point files.',
                'The README includes setup instructions, reflection, and the AI-generated method critique.',
            ],
        ],
        [
            'module' => 'Module 7',
            'slug' => 'module-7',
            'week' => 'Week 4',
            'week_number' => 4,
            'start' => 'Mon, Jul 13, 2026',
            'title' => 'Intro to Laravel',
            'description' => 'Move deeper into Laravel routes, controllers, Blade views, layouts, and framework conventions.',
            'status' => 'Open',
            'accent' => 'coral',
            'assignments' => [
                [
                    'label' => 'Assignment 7A',
                    'title' => 'Hello Route',
                    'description' => 'Create a standalone Laravel project, define static and parameterized routes, document the framework structure, and verify the work with tests and Git evidence.',
                    'status' => 'Ready',
                    'type' => 'Laravel Routing',
                    'url' => '/assignments/module7a',
                    'source' => 'assignments/module7a/routes/web.php',
                ],
                [
                    'label' => 'Assignment 7B',
                    'title' => 'Basic Routing',
                    'description' => 'Build a four-page personal Laravel website with closure and controller routes, a shared Blade layout, named navigation, a dynamic hobby parameter, and a custom 404 response.',
                    'status' => 'Ready',
                    'type' => 'Laravel MVC',
                    'url' => '/assignments/module7b',
                    'source' => 'assignments/module7b/routes/web.php',
                ],
            ],
            'resources' => ['Routes', 'Controllers', 'Blade layouts'],
            'notes' => [
                'This is the bridge from PHP fundamentals into a real Laravel application.',
                'Assignment 7A is a standalone Laravel application nested inside the coursework repository and mounted into the Module 7 roadmap.',
                'The required /hello and /greet/{name} routes are documented and protected by feature tests.',
                'Assignment 7B expands the routing exercise into a personal four-page site with closures, a controller, reusable Blade templates, and named navigation.',
            ],
        ],
        [
            'module' => 'Module 8',
            'slug' => 'module-8',
            'week' => 'Week 4',
            'week_number' => 4,
            'start' => 'Mon, Jul 13, 2026',
            'title' => 'ORM & Database Migrations (Eloquent)',
            'description' => 'Use Eloquent and migrations to describe, evolve, and query application data.',
            'status' => 'Open',
            'accent' => 'sky',
            'assignments' => [
                [
                    'label' => 'Assignment 8A',
                    'title' => 'Laravel with a Database Environment',
                    'description' => 'Configure a sanitized MySQL environment, run Laravel migrations, and verify the local connection with a read-only diagnostics query.',
                    'status' => 'Ready',
                    'type' => 'Laravel + MySQL',
                    'url' => '/assignments/module8a/database-environment.php',
                    'source' => 'assignments/module8a/README.md',
                ],
                [
                    'label' => 'Assignment 8B',
                    'title' => 'Inventory Rebuilt with Laravel Eloquent',
                    'description' => 'Rebuild the Module 4B inventory using a Laravel migration, the Item Eloquent model, a controller, Blade, and object-based filtering.',
                    'status' => 'Ready',
                    'type' => 'Eloquent + MySQL',
                    'url' => '/inventory',
                    'source' => 'assignments/module8b/README.md',
                ],
            ],
            'resources' => ['Laravel environment configuration', 'MySQL', 'Migrations', 'Eloquent models', 'Blade'],
            'notes' => [
                'Module 8A uses the existing CS85 Laravel application instead of nesting a duplicate framework project.',
                'The interactive page tests only a local MySQL host and runs a fixed read-only SELECT query.',
                'Module 8B rebuilds the earlier PDO inventory as a migration-managed Eloquent feature while preserving the original page for comparison.',
                'Real database passwords stay in the ignored local .env file and never enter Git.',
            ],
        ],
        [
            'module' => 'Module 9',
            'slug' => 'module-9',
            'week' => 'Week 5',
            'week_number' => 5,
            'start' => 'Mon, Jul 20, 2026',
            'title' => 'Full CRUD & Validation',
            'description' => 'Build create, read, update, and delete flows with validation rules and user feedback.',
            'status' => 'Open',
            'accent' => 'gold',
            'assignments' => [
                [
                    'label' => 'Assignment 9A',
                    'title' => 'Contact List App',
                    'description' => 'Load a default JSON dataset, query and filter contacts, then create, update, and delete records through a complete Laravel CRUD interface.',
                    'status' => 'Ready',
                    'type' => 'CRUD + Validation',
                    'route' => 'assignments.module9a.contacts.index',
                    'source' => 'assignments/module9a/README.md',
                ],
            ],
            'resources' => ['CRUD workflows', 'Form Requests', 'Eloquent relationships', 'JSON import', 'Validation errors'],
            'notes' => [
                'Assignment 9A uses separate contacts and contact_groups tables, so training actions cannot modify real authentication accounts.',
                'The workbench demonstrates GET filters, POST create/import, PUT update, and DELETE record/reset operations from one Blade UI.',
                'Sample contact roles are educational record data; they do not grant permissions in the real application.',
            ],
        ],
        [
            'module' => 'Module 10',
            'slug' => 'module-10',
            'week' => 'Week 5',
            'week_number' => 5,
            'start' => 'Mon, Jul 20, 2026',
            'title' => 'User Authentication',
            'description' => 'Add login, logout, protected screens, user-aware behavior, roles, and secure account flows.',
            'status' => 'Complete',
            'accent' => 'violet',
            'view' => 'pages.assignments.module10.user-authentication',
            'assignments' => [
                [
                    'label' => 'Assignment 10A',
                    'title' => 'User Authentication',
                    'description' => 'Document the Laravel authentication system implemented by this application, including sessions, protected routes, roles, and account security.',
                    'status' => 'Complete',
                    'type' => 'Laravel Auth',
                    'url' => '/roadmap/module-10',
                    'source' => 'resources/views/pages/assignments/module10/user-authentication.blade.php',
                ],
            ],
            'resources' => ['Laravel sessions', 'Authentication middleware', 'Email verification', 'Authorization and roles'],
            'notes' => [
                'The assignment is presented as a concise visual guide to the authentication already running in this application.',
                'The implementation goes beyond the core requirement with GitHub OAuth, TOTP MFA, recent-authentication step-up, session revocation, rate limits, and security audit events.',
            ],
        ],
        [
            'module' => 'Module 11',
            'slug' => 'module-11',
            'week' => 'Week 6',
            'week_number' => 6,
            'start' => 'Mon, Jul 27, 2026',
            'title' => 'Clean Architecture & Consuming APIs',
            'description' => 'Separate responsibilities and consume external APIs without mixing framework, domain, and presentation logic.',
            'status' => 'Scheduled',
            'accent' => 'teal',
            'assignments' => [],
            'resources' => ['Service classes', 'API clients', 'Clean boundaries'],
            'notes' => ['The Module 2B calendar is an early example: controller, service, and Blade view each have a job.'],
        ],
        [
            'module' => 'Module 12',
            'slug' => 'module-12',
            'week' => 'Week 6',
            'week_number' => 6,
            'start' => 'Mon, Jul 27, 2026',
            'title' => 'AI Integration, Career Tips & Final Project',
            'description' => 'Bring the course skills together with AI integration, portfolio polish, deployment notes, and final project planning.',
            'status' => 'Scheduled',
            'accent' => 'coral',
            'assignments' => [],
            'resources' => ['OpenAI integration', 'Career preparation', 'Final project polish'],
            'notes' => ['AI work should keep API keys server-side and make privacy/cost boundaries visible.'],
        ],
    ],

    'stack' => [
        [
            'category' => 'Application',
            'items' => ['PHP', 'Laravel', 'Blade', 'Vite'],
        ],
        [
            'category' => 'Data',
            'items' => ['SQLite for quick startup', 'MySQL-ready configuration', 'Migrations', 'Seeders'],
        ],
        [
            'category' => 'Quality',
            'items' => ['PHPUnit feature tests', 'Laravel Pint', 'npm audit', 'Build verification'],
        ],
        [
            'category' => 'Future AI',
            'items' => ['OpenAI PHP client', 'Server-side API key handling', 'Final project extension point'],
        ],
    ],

    'contact' => [
        'email' => 'serge.hall.dev@gmail.com',
        'profiles' => [
            [
                'label' => 'Coursework Website',
                'handle' => 'webdev-coursework.com',
                'href' => 'https://webdev-coursework.com',
                'description' => 'Learning reports, coursework progress, and web development portfolio notes.',
            ],
            [
                'label' => 'GitHub',
                'handle' => 'SergeHall',
                'href' => 'https://github.com/SergeHall',
                'description' => 'Code, backend systems, platform work, and shipping history.',
            ],
        ],
        'topics' => [
            'Course questions and CS85 assignment planning.',
            'Laravel architecture, database design, and backend implementation.',
            'AI-powered final project ideas and responsible API integration.',
            'Portfolio polish, deployment readiness, and GitHub presentation.',
        ],
    ],
];
